/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/musics/player`; params?: Router.UnknownInputParams; } | { pathname: `/musics${'/(modals)'}/addToPlaylist` | `/musics/addToPlaylist`; params?: Router.UnknownInputParams; } | { pathname: `/musics${'/(tabs)'}${'/(songs)'}` | `/musics`; params?: Router.UnknownInputParams; } | { pathname: `/musics${'/(tabs)'}/artists` | `/musics/artists`; params?: Router.UnknownInputParams; } | { pathname: `/musics${'/(tabs)'}/categories` | `/musics/categories`; params?: Router.UnknownInputParams; } | { pathname: `/news`; params?: Router.UnknownInputParams; } | { pathname: `/podcast`; params?: Router.UnknownInputParams; } | { pathname: `/radios`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `/musics${'/(tabs)'}/artists/[id]` | `/musics/artists/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/musics${'/(tabs)'}/categories/[id]` | `/musics/categories/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/musics/player`; params?: Router.UnknownOutputParams; } | { pathname: `/musics${'/(modals)'}/addToPlaylist` | `/musics/addToPlaylist`; params?: Router.UnknownOutputParams; } | { pathname: `/musics${'/(tabs)'}${'/(songs)'}` | `/musics`; params?: Router.UnknownOutputParams; } | { pathname: `/musics${'/(tabs)'}/artists` | `/musics/artists`; params?: Router.UnknownOutputParams; } | { pathname: `/musics${'/(tabs)'}/categories` | `/musics/categories`; params?: Router.UnknownOutputParams; } | { pathname: `/news`; params?: Router.UnknownOutputParams; } | { pathname: `/podcast`; params?: Router.UnknownOutputParams; } | { pathname: `/radios`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } } | { pathname: `/musics${'/(tabs)'}/artists/[id]` | `/musics/artists/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/musics${'/(tabs)'}/categories/[id]` | `/musics/categories/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/musics/player${`?${string}` | `#${string}` | ''}` | `/musics${'/(modals)'}/addToPlaylist${`?${string}` | `#${string}` | ''}` | `/musics/addToPlaylist${`?${string}` | `#${string}` | ''}` | `/musics${'/(tabs)'}${'/(songs)'}${`?${string}` | `#${string}` | ''}` | `/musics${`?${string}` | `#${string}` | ''}` | `/musics${'/(tabs)'}/artists${`?${string}` | `#${string}` | ''}` | `/musics/artists${`?${string}` | `#${string}` | ''}` | `/musics${'/(tabs)'}/categories${`?${string}` | `#${string}` | ''}` | `/musics/categories${`?${string}` | `#${string}` | ''}` | `/news${`?${string}` | `#${string}` | ''}` | `/podcast${`?${string}` | `#${string}` | ''}` | `/radios${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/musics/player`; params?: Router.UnknownInputParams; } | { pathname: `/musics${'/(modals)'}/addToPlaylist` | `/musics/addToPlaylist`; params?: Router.UnknownInputParams; } | { pathname: `/musics${'/(tabs)'}${'/(songs)'}` | `/musics`; params?: Router.UnknownInputParams; } | { pathname: `/musics${'/(tabs)'}/artists` | `/musics/artists`; params?: Router.UnknownInputParams; } | { pathname: `/musics${'/(tabs)'}/categories` | `/musics/categories`; params?: Router.UnknownInputParams; } | { pathname: `/news`; params?: Router.UnknownInputParams; } | { pathname: `/podcast`; params?: Router.UnknownInputParams; } | { pathname: `/radios`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | `/musics${'/(tabs)'}/artists/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/musics/artists/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/musics${'/(tabs)'}/categories/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/musics/categories/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `/musics${'/(tabs)'}/artists/[id]` | `/musics/artists/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/musics${'/(tabs)'}/categories/[id]` | `/musics/categories/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
